import "./globals.css";
import Provider from "./provider";

export const metadata = {
  title: "Zustand Practice with Chakra UI - Juan Carlos Lumingkit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
